DROP TABLE IF EXISTS DOCKERDB.ENTITYBUS;
CREATE TABLE DOCKERDB.ENTITYBUS
(
    EID INT PRIMARY KEY,
    ENUMBER VARCHAR(255)
);

-- Insert some dummy data
INSERT INTO ENTITYBUS ( EID, ENUMBER ) VALUES("1","111");
INSERT INTO ENTITYBUS ( EID, ENUMBER ) VALUES("2","222");
INSERT INTO ENTITYBUS ( EID, ENUMBER ) VALUES("3","333");
